variables:
  REPO_NAME: gitlab.com/yashmehrotra/neodyeus
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

stages:
    - test
    - build

format:
    stage: test
    image: golang:latest
    script:
      - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
      - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
      - cd $GOPATH/src/$REPO_NAME
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure
      - go fmt $(go list ./... | grep -v /vendor/)
      - go vet $(go list ./... | grep -v /vendor/)
      - go test -race $(go list ./... | grep -v /vendor/)

compile:
    stage: build
    image: docker:stable
    only:
      - master
    services:
      - docker:dind
    script:
      - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
      - docker build -t registry.gitlab.com/yashmehrotra/neodyeus:master .
      - docker push registry.gitlab.com/yashmehrotra/neodyeus:master
